---
title: "Synthetic data example"
author: "Enrico Zorzetto"
date: "5/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(nleqslv)
library(extraDistr)
library(ggplot2)
library(tidyr)
library(dplyr)
library(gridExtra)
library(rstan)
library(bayesplot)
library(loo)
library(hmevr)
options(mc.cores = parallel::detectCores())

init_time = proc.time()
# set seed for reproducible example:
set.seed(1)

# outplot1 = file.path('..', 'output')
# dir.create(outplot1, showWarnings = FALSE)
# outplot = file.path('..', 'output', 'outplot')
# dir.create(outplot, showWarnings = FALSE)
```

Set parameters for analysis
```{r setparam}
niter = 2000
nchains = 4
ndraws = niter*nchains/2
Mgen = 50 # number of sample points to average over latent level variables
trmin = 2 # minimum return times for which quantiles are computed
Nt = 366 # number of obs / block (days / year)

# generate synthetic data: length of validation and calibration datasets
Mval = 200
Mcal1 = 20
Mcal2 = 50

# true parameters and model specification for generating datasets:
# wtrue = 1
# ctrue = 10

mctrue = 6
sctrue = 1
mwtrue = 1
swtrue = 0.1

pntrue = 0.3

max_treedepth = 10

myptrue = list(mc = mctrue, sc = sctrue, mw = mwtrue, sw = swtrue)
# myptrue = list(C = ctrue, w = wtrue)
myntrue = list(pn = pntrue)

ndistr = 'bin'
pdistr = 'wei_dgu'
# pdistr = 'wei'
################################################################################

# generate data
cdata1 = load_synth_data(Mcal1,
            ptrue = myptrue,
            ntrue = myntrue,
            Nt = Nt,
            ndist = ndistr, dist = pdistr)

cdata2 = load_synth_data(Mcal2,
            ptrue = myptrue,
            ntrue = myntrue,
            Nt = Nt,
            ndist = ndistr, dist = pdistr)

vdata = load_synth_data(Mval,
            ptrue = myptrue,
            ntrue = myntrue,
            Nt = Nt,
            ndist = ndistr, dist = pdistr)
```


Fit the EV models to the two samples 
```{r fit}
dgu_prpar = list(gu_exp_sc0 = 0.25, gu_exp_sw0 = 0.05, # by default 0.25, 0.05
                 inf_sc0 =10, inf_sw0 = 10, # by default is 100
                inf_mc0 = 10, inf_mw0 = 10) # by default is 10
dynfit1 = fit_ev_model(cdata1$data, model = 'wei_dgu_bin',  
                       iter = niter, chains = nchains, Mgen = Mgen,
                       max_treedepth = max_treedepth, priorpar = dgu_prpar)
# stafit1 = fit_ev_model(cdata1$data, model = 'wei_sta_bin',  
#                      iter = niter, chains = nchains, Mgen = Mgen)
potfit1 = fit_ev_model(cdata1$data, model = 'pot_ppp',          
                       iter = niter, chains = nchains, Mgen = Mgen,
                       max_treedepth = max_treedepth)
gevfit1 = fit_ev_model(cdata1$data, model = 'gev',          
                       iter = niter, chains = nchains, Mgen = Mgen,
                       max_treedepth = max_treedepth)

dynfit2 = fit_ev_model(cdata2$data, model = 'wei_dgu_bin',  
                       iter = niter, chains = nchains, Mgen = Mgen, 
                       draw_priors = TRUE, 
                       max_treedepth = max_treedepth, priorpar = dgu_prpar)
# stafit2 = fit_ev_model(cdata2$data, model = 'wei_sta_bin',  
#                      iter = niter, chains = nchains, Mgen = Mgen)
potfit2 = fit_ev_model(cdata2$data, model = 'pot_ppp',          
                       iter = niter, chains = nchains, Mgen = Mgen,
                       max_treedepth = max_treedepth)
gevfit2 = fit_ev_model(cdata2$data, model = 'gev',          
                       iter = niter, chains = nchains, Mgen = Mgen, 
                       max_treedepth = max_treedepth)
```

To take a look at the results:
dynsim = rstan::extract(dynfit$model_fit)
stasim = rstan::extract(stafit$model_fit)

Compute quantiles and goodness of fit measures
```{r quants}
dynq1 = comp_quant(dynfit1, vdata$maxima, trmin = trmin)
# staq1 = comp_quant(stafit1, vdata$maxima, trmin = trmin)
potq1 = comp_quant(potfit1, vdata$maxima, trmin = trmin)
gevq1 = comp_quant(gevfit1, vdata$maxima, trmin = trmin)

dynq2 = comp_quant(dynfit2, vdata$maxima, trmin = trmin)
# staq2 = comp_quant(stafit2, vdata$maxima, trmin = trmin)
potq2 = comp_quant(potfit2, vdata$maxima, trmin = trmin)
gevq2 = comp_quant(gevfit2, vdata$maxima, trmin = trmin)
```

```{r plotquants}
trtrue = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 15, 20, 30, 40, 50,75, 100, 125, 150, 200)
qutrue = qhbev(trtrue, ntrue = myntrue, ptrue = myptrue, nsamples = 500, 
               ndistr = ndistr, pdistr = pdistr, Nt = Nt, Tr = TRUE)

    
    linesize = 0.7
    shadealpha = 0.4
    # colmodels <- c("GEV"="red","PPP"="green","HBEV"="blue")
    p1 <- ggplot() +
      # geom_line(aes(gevq1$TrvalQ, gevq1$qmean),  
      #             linetype="solid",color= "red", size = linesize) +
        geom_ribbon(aes(x = gevq1$TrvalQ, 
                  ymax = gevq1$qupper, ymin = gevq1$qlower),  
                  alpha = shadealpha,  fill = "red") +
      geom_line(aes(gevq1$TrvalQ, gevq1$qupper), linetype="dotted",color="red") +
      geom_line(aes(gevq1$TrvalQ, gevq1$qlower), linetype="dotted",color="red") +
    
          geom_ribbon(aes(x = potq1$TrvalQ, 
                  ymax = potq1$qupper, ymin = potq1$qlower),  
                  alpha = shadealpha,  fill = "green") +
      geom_line(aes(potq1$TrvalQ, potq1$qupper), linetype="dotted",color="green") +
      geom_line(aes(potq1$TrvalQ, potq1$qlower), linetype="dotted",color="green") +
      
            geom_ribbon(aes(x = dynq1$TrvalQ, 
                  ymax = dynq1$qupper, ymin = dynq1$qlower),  
                  alpha = shadealpha,  fill = "blue") +
      geom_line(aes(dynq1$TrvalQ, dynq1$qupper), linetype="dotted",color="blue") +
      geom_line(aes(dynq1$TrvalQ, dynq1$qlower), linetype="dotted",color="blue") +
    
      geom_line(aes(gevq1$TrvalQ, gevq1$qmean, color= "red"),  
                linetype="dotdash", size = linesize) +
      geom_line(aes(potq1$TrvalQ, potq1$qmean, color= "green"),  
                linetype="twodash", size = linesize) +
      geom_line(aes(dynq1$TrvalQ, dynq1$qmean, color= "blue"),  
                linetype="solid",size = linesize) +
      
      
      scale_color_identity(element_blank(),
                           # name = "Model fit",
                           breaks = c("red", "green", "blue"),
                           labels = c("GEV", "POT", "HMEV"),
                           guide = "legend") +
      
        geom_point(aes( cdata1$Tr, cdata1$Xi), 
                color = 'black', shape = 1, size = 3.4, stroke = 1.2) +
      # geom_point(aes( vdata$Tr, vdata$Xi),
      #          size = 1.5,   color = 'black', shape = 2) +
      # geom_line(aes( tri_true, xxi),  linetype="solid",   
                # color = 'black', size = 1.2*linesize) +
        geom_line(aes( trtrue, qutrue),  linetype="solid",   
                color = 'black', size = 1.2*linesize) +
      # geom_line(aes( tri_true, xxi),  linetype="solid",   color = 'black') +
    
    
      annotate("text", x=2.5, y=180, label="a)", size = 8) +
      # coord_trans(x="log10", y='log10') +
      coord_trans(x="log10") +
      labs(y = "Quantile [mm/day]", x= "Return Time [years]") +
      theme_bw() + 
    
      scale_x_continuous(breaks=c(2, 5, 10, 20, 50, 100, 200), limits = c(2, 202)) +
      # scale_y_continuous(limits=c(0, 200)) +
      theme(legend.position = c(0.35, 0.8),
            legend.background = element_blank(),
            text = element_text(size=14),
            legend.box.background = element_rect(colour = "black")
            ) 
    
    
    
    p2 <- ggplot() +
    
      
      geom_ribbon(aes(x = gevq2$TrvalQ, 
                  ymax = gevq2$qupper, ymin = gevq2$qlower),  
                  alpha = shadealpha,  fill = "red") +
      geom_line(aes(gevq2$TrvalQ, gevq2$qupper), linetype="dotted",color="red") +
      geom_line(aes(gevq2$TrvalQ, gevq2$qlower), linetype="dotted",color="red") +
      
        geom_ribbon(aes(x = potq2$TrvalQ, 
                  ymax = potq2$qupper, ymin = potq2$qlower),  
                  alpha = shadealpha,  fill = "green") +
      geom_line(aes(potq2$TrvalQ, potq2$qupper), linetype="dotted",color="green") +
      geom_line(aes(potq2$TrvalQ, potq2$qlower), linetype="dotted",color="green") +
      
          geom_ribbon(aes(x = dynq2$TrvalQ, 
                  ymax = dynq2$qupper, ymin = dynq2$qlower),  
                  alpha = shadealpha,  fill = "blue") +
      geom_line(aes(dynq2$TrvalQ, dynq2$qupper), linetype="dotted",color="blue") +
      geom_line(aes(dynq2$TrvalQ, dynq2$qlower), linetype="dotted",color="blue") +
      
      
      geom_line(aes(gevq2$TrvalQ, gevq2$qmean),  
                linetype="dotdash",color= "red",   size = linesize) +
      geom_line(aes(potq2$TrvalQ, potq2$qmean),  
                linetype="twodash",color= "green", size = linesize) +
      geom_line(aes(dynq2$TrvalQ, dynq2$qmean),  
                linetype="solid",color= "blue",  size = linesize) +
      
        geom_point(aes(cdata2$Tr, cdata2$Xi), 
                 color='black', shape=1, size = 3.4, stroke = 1.2) +
      # geom_point(aes( vdata$Tr, vdata$Xi),
      #          size = 1.5,   color = 'black', shape = 2) +
      # geom_line(aes( tri_true, xxi),  linetype="solid",   
                # color = 'black', size = 1.2*linesize) +
          geom_line(aes( trtrue, qutrue),  linetype="solid",   
                color = 'black', size = 1.2*linesize) +
    
    
      # coord_trans(x="log10", y='log10') +
      # annotate("text", x=2.5, y=max(gevq2$qupper), label="b)", size = 8) +
      # annotate("text", x=2.5, y=180, label="b)", size = 8) +
      coord_trans(x="log10") +
      labs(y = "Quantile [mm/day]", x= "Return Time [years]") +
      theme_bw() +
    
      # scale_y_continuous(limits=c(0, 200)) +
      scale_x_continuous(breaks=c(2, 5, 10, 20, 50, 100, 200),   
                         limits = c(2, 202))+ 
    
          theme(
            # legend.position = c(0.35, 0.8),
            # legend.background = element_blank(),
            text = element_text(size=14),
            # legend.box.background = element_rect(colour = "black")
            ) 
    
    fig1 <- grid.arrange(p1, p2, ncol=2)
    # outplot = file.path('../output/outplot')
    # ggsave(file.path(outplot, 'synth_examples_ss_20_50.png'), 
           # plot=fig1, device = 'png', width = 8, height = 4.2)
```    


Plot true and estimated parameters

```{r predchecks}
fit = dynfit2
quants = dynq2
sim = rstan::extract(fit$model_fit)
max_sim = hbev_max_ppd(fit)
sdata = cdata2




ppc1 <- ppc_dens_overlay( log(sdata$maxima), 
                          log(max_sim)[1:50,]) + labs(x="log(maxima)")



true_pars = c(mc = mctrue, sc = sctrue, mw = mwtrue, sw = swtrue, pn = pntrue)

draws = as.data.frame(sim)[c("mc", "sc", "mw", "sw", "pn")]




# priors = as.data.frame(priorlist$prior_rng)
priors = as.data.frame(fit$prior$prior_rng)

# compare parameters draws with 'true' value
color_scheme_set("brightblue")
pp1 <-mcmc_recover_hist(draws, true_pars)  




pp2 <- ggplot(gather(priors), aes(value)) + 
  geom_histogram(bins = 30) + 
  facet_wrap(~key, scales = 'free_x')

fig2 <- grid.arrange(pp1, pp2)
 # ggsave(file.path(outplot, 'wei_synth_pdfs.png'), plot=fig2, device = 'png',
                        # width = 6, height = 6) 
```

