---
title: "synth_analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{synth_analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(hbevr)
library(nleqslv)
library(extraDistr)
library(ggplot2)
library(bayesplot)
library(tidyr)
library(gridExtra)
```

Generate synthetic data according to a Gumbel-Weibull dynamical model
```{r}
niter = 2000
nchains = 4
ndraws = niter*nchains/2

# generate synthetic data:
Mgen = 

mctrue = 10
sctrue = 3
mwtrue = 0.7
swtrue = 0.1
pntrue = 0.3
wtrue = 0.7
ctrue = 10
sdata = load_synth_data(Mgen, 
                        # ptrue = list(ac = actrue, bc = bctrue, aw = awtrue,bw = bwtrue),
                        # ptrue = list(mc = mctrue, sc = sctrue, mw = mwtrue, sw = swtrue),
                        ptrue = list(w=wtrue, C = ctrue),
                        # ptrue = list(w=truew, C = truec), 
                        ntrue = list(pn = pntrue), 
                        Nt = 366,
                        ndist = 'bin',
                        dist = 'wei')
                        # dist = 'wei_dgu')
```

```{r}
# fit the GEV model 
fit = fit_ev_model(sdata$data, model = 'wei_dgu_bin',  
                   iter = niter, chains = nchains, Mgen = Mgen,
                   draw_priors = TRUE)

sim = rstan::extract(fit$model_fit)


quants = comp_quant(fit, sdata$maxima, trmin = 2)

max_sim = hbev_max_ppd(fit)

```


```{r}



clrs <- bayesplot::color_scheme_get("brightblue")
ggplot() +
  geom_point(aes( quants$TrvalQ, quants$XivalQ),  size = 1.5, color = clrs[[6]]) +
  geom_line(aes(  quants$TrvalQ, quants$qmean),  linetype="solid",color="black") +
  geom_line(aes(  quants$TrvalQ, quants$qupper), linetype="dashed",color="black") +
  geom_line(aes(  quants$TrvalQ, quants$qlower), linetype="dashed",color="black") +
  coord_trans(x="log10") +
  labs(y = "Quantile [mm/day]", x= "Return Time [years]") +
  theme_bw()


# plot the cdfs of the parameters:
# ggplot()+
# # p <- ggplot(df, aes(x=weight)) + 
#   geom_density(aes(x=sim$C), color="darkblue", fill="lightblue") + 
#   geom_vline(truec, 'dashed', 'blue', 4)
```

```{r}
ppc1 <- ppc_dens_overlay( log(sdata$maxima), log(max_sim)[1:50,]) + labs(x="log(maxima)")


# ppc2 <- ppc_dens_overlay( rep(mctrue, 100) , sim$Cgen[1:50,]) + labs(x="C")+
#   vline_at(mctrue)

# true_pars = list(c = truec, w = truew)
true_pars = c(mc = mctrue, sc = sctrue, mw = mwtrue, sw = swtrue, pn = pntrue)
# true_pars = c(ac = actrue, bc = bctrue, aw = awtrue, bw = bwtrue)

# draws = as.data.frame(sim)[c("ac", "bc", "aw", "bw")]
draws = as.data.frame(sim)[c("mc", "sc", "mw", "sw", "pn")]
# draw_pars = list(draws, w = sim$wgen[1:50,1])


# plot priors:
# priorlist = hbev_priors(fit$model, data = sdata$data, 
#                         empirical = TRUE, thresh_hbev = fit$thresh_hbev,
#                         draw_rng = TRUE, ndraws = 4000)

# hist(priorlist$prior_rng$mc)
hist(fit$prior$prior_rng$mc)

# priors = as.data.frame(priorlist$prior_rng)
priors = as.data.frame(fit$prior$prior_rng)

```

```{r}
# compare parameters draws with 'true' value
color_scheme_set("brightblue")
fig1 <-mcmc_recover_hist(draws, true_pars)  

# fig2 <-ppc_dens_overlay(priors['p0'], draws['p0'])



fig2 <- ggplot(gather(priors), aes(value)) + 
  geom_histogram(bins = 30) + 
  facet_wrap(~key, scales = 'free_x')

grid.arrange(fig1, fig2)
```
