// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4gev_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gev_nobounds_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mix_dyn_bin_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mix_dyp_bin_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mix_sta_bin_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4pot_ppp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4wei_dex_bin_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4wei_dgu_bin_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4wei_dsn_bin_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4wei_dyl_bin_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4wei_dyn_bbn_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4wei_dyn_bin_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4wei_sta_bbn_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4wei_sta_bin_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4gev_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gev_mod, 0},
    {"_rcpp_module_boot_stan_fit4gev_nobounds_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gev_nobounds_mod, 0},
    {"_rcpp_module_boot_stan_fit4mix_dyn_bin_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mix_dyn_bin_mod, 0},
    {"_rcpp_module_boot_stan_fit4mix_dyp_bin_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mix_dyp_bin_mod, 0},
    {"_rcpp_module_boot_stan_fit4mix_sta_bin_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mix_sta_bin_mod, 0},
    {"_rcpp_module_boot_stan_fit4pot_ppp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4pot_ppp_mod, 0},
    {"_rcpp_module_boot_stan_fit4wei_dex_bin_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4wei_dex_bin_mod, 0},
    {"_rcpp_module_boot_stan_fit4wei_dgu_bin_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4wei_dgu_bin_mod, 0},
    {"_rcpp_module_boot_stan_fit4wei_dsn_bin_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4wei_dsn_bin_mod, 0},
    {"_rcpp_module_boot_stan_fit4wei_dyl_bin_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4wei_dyl_bin_mod, 0},
    {"_rcpp_module_boot_stan_fit4wei_dyn_bbn_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4wei_dyn_bbn_mod, 0},
    {"_rcpp_module_boot_stan_fit4wei_dyn_bin_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4wei_dyn_bin_mod, 0},
    {"_rcpp_module_boot_stan_fit4wei_sta_bbn_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4wei_sta_bbn_mod, 0},
    {"_rcpp_module_boot_stan_fit4wei_sta_bin_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4wei_sta_bin_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_hbevr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
