// Generated by rstantools.  Do not edit by hand.

/*
    hbevr is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    hbevr is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with hbevr.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_wei_dsn_bin_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_wei_dsn_bin");
    reader.add_event(187, 185, "end", "model_wei_dsn_bin");
    return reader;
}
#include <stan_meta_header.hpp>
class model_wei_dsn_bin : public prob_grad {
private:
        int M;
        int Mgen;
        int Nt;
        std::vector<std::vector<double> > y;
        std::vector<int> N;
        std::vector<double> csnloc0prior;
        std::vector<double> wsnloc0prior;
        std::vector<double> csnsc0prior;
        std::vector<double> wsnsc0prior;
        std::vector<double> csnsh0prior;
        std::vector<double> wsnsh0prior;
        std::vector<double> pn0prior;
public:
    model_wei_dsn_bin(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_wei_dsn_bin(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_wei_dsn_bin_namespace::model_wei_dsn_bin";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 28;
            context__.validate_dims("data initialization", "M", "int", context__.to_vec());
            M = int(0);
            vals_i__ = context__.vals_i("M");
            pos__ = 0;
            M = vals_i__[pos__++];
            check_greater_or_equal(function__, "M", M, 1);
            current_statement_begin__ = 29;
            context__.validate_dims("data initialization", "Mgen", "int", context__.to_vec());
            Mgen = int(0);
            vals_i__ = context__.vals_i("Mgen");
            pos__ = 0;
            Mgen = vals_i__[pos__++];
            check_greater_or_equal(function__, "Mgen", Mgen, 1);
            current_statement_begin__ = 30;
            context__.validate_dims("data initialization", "Nt", "int", context__.to_vec());
            Nt = int(0);
            vals_i__ = context__.vals_i("Nt");
            pos__ = 0;
            Nt = vals_i__[pos__++];
            check_greater_or_equal(function__, "Nt", Nt, 1);
            current_statement_begin__ = 31;
            validate_non_negative_index("y", "M", M);
            validate_non_negative_index("y", "Nt", Nt);
            context__.validate_dims("data initialization", "y", "double", context__.to_vec(M,Nt));
            y = std::vector<std::vector<double> >(M, std::vector<double>(Nt, double(0)));
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_k_0_max__ = M;
            size_t y_k_1_max__ = Nt;
            for (size_t k_1__ = 0; k_1__ < y_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < y_k_0_max__; ++k_0__) {
                    y[k_0__][k_1__] = vals_r__[pos__++];
                }
            }
            size_t y_i_0_max__ = M;
            size_t y_i_1_max__ = Nt;
            for (size_t i_0__ = 0; i_0__ < y_i_0_max__; ++i_0__) {
                for (size_t i_1__ = 0; i_1__ < y_i_1_max__; ++i_1__) {
                    check_greater_or_equal(function__, "y[i_0__][i_1__]", y[i_0__][i_1__], 0);
                }
            }
            current_statement_begin__ = 32;
            validate_non_negative_index("N", "M", M);
            context__.validate_dims("data initialization", "N", "int", context__.to_vec(M));
            N = std::vector<int>(M, int(0));
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            size_t N_k_0_max__ = M;
            for (size_t k_0__ = 0; k_0__ < N_k_0_max__; ++k_0__) {
                N[k_0__] = vals_i__[pos__++];
            }
            size_t N_i_0_max__ = M;
            for (size_t i_0__ = 0; i_0__ < N_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "N[i_0__]", N[i_0__], 0);
            }
            current_statement_begin__ = 42;
            validate_non_negative_index("csnloc0prior", "2", 2);
            context__.validate_dims("data initialization", "csnloc0prior", "double", context__.to_vec(2));
            csnloc0prior = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("csnloc0prior");
            pos__ = 0;
            size_t csnloc0prior_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < csnloc0prior_k_0_max__; ++k_0__) {
                csnloc0prior[k_0__] = vals_r__[pos__++];
            }
            size_t csnloc0prior_i_0_max__ = 2;
            for (size_t i_0__ = 0; i_0__ < csnloc0prior_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "csnloc0prior[i_0__]", csnloc0prior[i_0__], 0);
            }
            current_statement_begin__ = 43;
            validate_non_negative_index("wsnloc0prior", "2", 2);
            context__.validate_dims("data initialization", "wsnloc0prior", "double", context__.to_vec(2));
            wsnloc0prior = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("wsnloc0prior");
            pos__ = 0;
            size_t wsnloc0prior_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < wsnloc0prior_k_0_max__; ++k_0__) {
                wsnloc0prior[k_0__] = vals_r__[pos__++];
            }
            size_t wsnloc0prior_i_0_max__ = 2;
            for (size_t i_0__ = 0; i_0__ < wsnloc0prior_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "wsnloc0prior[i_0__]", wsnloc0prior[i_0__], 0);
            }
            current_statement_begin__ = 44;
            validate_non_negative_index("csnsc0prior", "2", 2);
            context__.validate_dims("data initialization", "csnsc0prior", "double", context__.to_vec(2));
            csnsc0prior = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("csnsc0prior");
            pos__ = 0;
            size_t csnsc0prior_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < csnsc0prior_k_0_max__; ++k_0__) {
                csnsc0prior[k_0__] = vals_r__[pos__++];
            }
            size_t csnsc0prior_i_0_max__ = 2;
            for (size_t i_0__ = 0; i_0__ < csnsc0prior_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "csnsc0prior[i_0__]", csnsc0prior[i_0__], 0);
            }
            current_statement_begin__ = 45;
            validate_non_negative_index("wsnsc0prior", "2", 2);
            context__.validate_dims("data initialization", "wsnsc0prior", "double", context__.to_vec(2));
            wsnsc0prior = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("wsnsc0prior");
            pos__ = 0;
            size_t wsnsc0prior_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < wsnsc0prior_k_0_max__; ++k_0__) {
                wsnsc0prior[k_0__] = vals_r__[pos__++];
            }
            size_t wsnsc0prior_i_0_max__ = 2;
            for (size_t i_0__ = 0; i_0__ < wsnsc0prior_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "wsnsc0prior[i_0__]", wsnsc0prior[i_0__], 0);
            }
            current_statement_begin__ = 46;
            validate_non_negative_index("csnsh0prior", "2", 2);
            context__.validate_dims("data initialization", "csnsh0prior", "double", context__.to_vec(2));
            csnsh0prior = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("csnsh0prior");
            pos__ = 0;
            size_t csnsh0prior_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < csnsh0prior_k_0_max__; ++k_0__) {
                csnsh0prior[k_0__] = vals_r__[pos__++];
            }
            size_t csnsh0prior_i_0_max__ = 2;
            for (size_t i_0__ = 0; i_0__ < csnsh0prior_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "csnsh0prior[i_0__]", csnsh0prior[i_0__], 0);
            }
            current_statement_begin__ = 47;
            validate_non_negative_index("wsnsh0prior", "2", 2);
            context__.validate_dims("data initialization", "wsnsh0prior", "double", context__.to_vec(2));
            wsnsh0prior = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("wsnsh0prior");
            pos__ = 0;
            size_t wsnsh0prior_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < wsnsh0prior_k_0_max__; ++k_0__) {
                wsnsh0prior[k_0__] = vals_r__[pos__++];
            }
            size_t wsnsh0prior_i_0_max__ = 2;
            for (size_t i_0__ = 0; i_0__ < wsnsh0prior_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "wsnsh0prior[i_0__]", wsnsh0prior[i_0__], 0);
            }
            current_statement_begin__ = 48;
            validate_non_negative_index("pn0prior", "2", 2);
            context__.validate_dims("data initialization", "pn0prior", "double", context__.to_vec(2));
            pn0prior = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("pn0prior");
            pos__ = 0;
            size_t pn0prior_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < pn0prior_k_0_max__; ++k_0__) {
                pn0prior[k_0__] = vals_r__[pos__++];
            }
            size_t pn0prior_i_0_max__ = 2;
            for (size_t i_0__ = 0; i_0__ < pn0prior_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "pn0prior[i_0__]", pn0prior[i_0__], 0);
            }
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 56;
            validate_non_negative_index("C", "M", M);
            num_params_r__ += (1 * M);
            current_statement_begin__ = 57;
            validate_non_negative_index("w", "M", M);
            num_params_r__ += (1 * M);
            current_statement_begin__ = 58;
            num_params_r__ += 1;
            current_statement_begin__ = 59;
            num_params_r__ += 1;
            current_statement_begin__ = 60;
            num_params_r__ += 1;
            current_statement_begin__ = 61;
            num_params_r__ += 1;
            current_statement_begin__ = 62;
            num_params_r__ += 1;
            current_statement_begin__ = 63;
            num_params_r__ += 1;
            current_statement_begin__ = 68;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_wei_dsn_bin() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 56;
        if (!(context__.contains_r("C")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable C missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("C");
        pos__ = 0U;
        validate_non_negative_index("C", "M", M);
        context__.validate_dims("parameter initialization", "C", "double", context__.to_vec(M));
        std::vector<double> C(M, double(0));
        size_t C_k_0_max__ = M;
        for (size_t k_0__ = 0; k_0__ < C_k_0_max__; ++k_0__) {
            C[k_0__] = vals_r__[pos__++];
        }
        size_t C_i_0_max__ = M;
        for (size_t i_0__ = 0; i_0__ < C_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, C[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable C: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 57;
        if (!(context__.contains_r("w")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable w missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("w");
        pos__ = 0U;
        validate_non_negative_index("w", "M", M);
        context__.validate_dims("parameter initialization", "w", "double", context__.to_vec(M));
        std::vector<double> w(M, double(0));
        size_t w_k_0_max__ = M;
        for (size_t k_0__ = 0; k_0__ < w_k_0_max__; ++k_0__) {
            w[k_0__] = vals_r__[pos__++];
        }
        size_t w_i_0_max__ = M;
        for (size_t i_0__ = 0; i_0__ < w_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, w[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable w: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 58;
        if (!(context__.contains_r("cloc")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable cloc missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("cloc");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "cloc", "double", context__.to_vec());
        double cloc(0);
        cloc = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, cloc);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable cloc: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 59;
        if (!(context__.contains_r("wloc")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable wloc missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("wloc");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "wloc", "double", context__.to_vec());
        double wloc(0);
        wloc = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, wloc);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable wloc: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 60;
        if (!(context__.contains_r("csc")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable csc missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("csc");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "csc", "double", context__.to_vec());
        double csc(0);
        csc = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, csc);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable csc: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 61;
        if (!(context__.contains_r("wsc")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable wsc missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("wsc");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "wsc", "double", context__.to_vec());
        double wsc(0);
        wsc = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, wsc);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable wsc: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 62;
        if (!(context__.contains_r("csh")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable csh missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("csh");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "csh", "double", context__.to_vec());
        double csh(0);
        csh = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, csh);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable csh: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 63;
        if (!(context__.contains_r("wsh")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable wsh missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("wsh");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "wsh", "double", context__.to_vec());
        double wsh(0);
        wsh = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, wsh);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable wsh: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 68;
        if (!(context__.contains_r("pn")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable pn missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("pn");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "pn", "double", context__.to_vec());
        double pn(0);
        pn = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, 1, pn);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable pn: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 56;
            std::vector<local_scalar_t__> C;
            size_t C_d_0_max__ = M;
            C.reserve(C_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < C_d_0_max__; ++d_0__) {
                if (jacobian__)
                    C.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    C.push_back(in__.scalar_lb_constrain(0));
            }
            current_statement_begin__ = 57;
            std::vector<local_scalar_t__> w;
            size_t w_d_0_max__ = M;
            w.reserve(w_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < w_d_0_max__; ++d_0__) {
                if (jacobian__)
                    w.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    w.push_back(in__.scalar_lb_constrain(0));
            }
            current_statement_begin__ = 58;
            local_scalar_t__ cloc;
            (void) cloc;  // dummy to suppress unused var warning
            if (jacobian__)
                cloc = in__.scalar_lb_constrain(0, lp__);
            else
                cloc = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 59;
            local_scalar_t__ wloc;
            (void) wloc;  // dummy to suppress unused var warning
            if (jacobian__)
                wloc = in__.scalar_lb_constrain(0, lp__);
            else
                wloc = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 60;
            local_scalar_t__ csc;
            (void) csc;  // dummy to suppress unused var warning
            if (jacobian__)
                csc = in__.scalar_lb_constrain(0, lp__);
            else
                csc = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 61;
            local_scalar_t__ wsc;
            (void) wsc;  // dummy to suppress unused var warning
            if (jacobian__)
                wsc = in__.scalar_lb_constrain(0, lp__);
            else
                wsc = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 62;
            local_scalar_t__ csh;
            (void) csh;  // dummy to suppress unused var warning
            if (jacobian__)
                csh = in__.scalar_lb_constrain(0, lp__);
            else
                csh = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 63;
            local_scalar_t__ wsh;
            (void) wsh;  // dummy to suppress unused var warning
            if (jacobian__)
                wsh = in__.scalar_lb_constrain(0, lp__);
            else
                wsh = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 68;
            local_scalar_t__ pn;
            (void) pn;  // dummy to suppress unused var warning
            if (jacobian__)
                pn = in__.scalar_lub_constrain(0, 1, lp__);
            else
                pn = in__.scalar_lub_constrain(0, 1);
            // model body
            current_statement_begin__ = 90;
            lp_accum__.add(beta_log<propto__>(pn, get_base1(pn0prior, 1, "pn0prior", 1), get_base1(pn0prior, 2, "pn0prior", 1)));
            current_statement_begin__ = 93;
            lp_accum__.add(gamma_log<propto__>(cloc, get_base1(csnloc0prior, 1, "csnloc0prior", 1), get_base1(csnloc0prior, 2, "csnloc0prior", 1)));
            current_statement_begin__ = 94;
            lp_accum__.add(gamma_log<propto__>(wloc, get_base1(wsnloc0prior, 1, "wsnloc0prior", 1), get_base1(wsnloc0prior, 2, "wsnloc0prior", 1)));
            current_statement_begin__ = 95;
            lp_accum__.add(gamma_log<propto__>(csc, get_base1(csnsc0prior, 1, "csnsc0prior", 1), get_base1(csnsc0prior, 2, "csnsc0prior", 1)));
            current_statement_begin__ = 96;
            lp_accum__.add(gamma_log<propto__>(wsc, get_base1(wsnsc0prior, 1, "wsnsc0prior", 1), get_base1(wsnsc0prior, 2, "wsnsc0prior", 1)));
            current_statement_begin__ = 97;
            lp_accum__.add(gamma_log<propto__>(csh, get_base1(csnsh0prior, 1, "csnsh0prior", 1), get_base1(csnsh0prior, 2, "csnsh0prior", 1)));
            current_statement_begin__ = 98;
            lp_accum__.add(gamma_log<propto__>(wsh, get_base1(wsnsh0prior, 1, "wsnsh0prior", 1), get_base1(wsnsh0prior, 2, "wsnsh0prior", 1)));
            current_statement_begin__ = 107;
            for (int m = 1; m <= M; ++m) {
                current_statement_begin__ = 112;
                lp_accum__.add(skew_normal_log<propto__>(get_base1(C, m, "C", 1), cloc, csc, csh));
                current_statement_begin__ = 113;
                lp_accum__.add(skew_normal_log<propto__>(get_base1(w, m, "w", 1), wloc, wsc, wsh));
                current_statement_begin__ = 114;
                lp_accum__.add(binomial_log(get_base1(N, m, "N", 1), Nt, pn));
                current_statement_begin__ = 115;
                for (int j = 1; j <= Nt; ++j) {
                    current_statement_begin__ = 116;
                    if (as_bool(logical_gt(get_base1(get_base1(y, m, "y", 1), j, "y", 2), 1e-6))) {
                        current_statement_begin__ = 117;
                        lp_accum__.add(weibull_log<propto__>(get_base1(get_base1(y, m, "y", 1), j, "y", 2), get_base1(w, m, "w", 1), get_base1(C, m, "C", 1)));
                    }
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("C");
        names__.push_back("w");
        names__.push_back("cloc");
        names__.push_back("wloc");
        names__.push_back("csc");
        names__.push_back("wsc");
        names__.push_back("csh");
        names__.push_back("wsh");
        names__.push_back("pn");
        names__.push_back("Ngen");
        names__.push_back("Cgen");
        names__.push_back("wgen");
        names__.push_back("count_w");
        names__.push_back("genw");
        names__.push_back("count_c");
        names__.push_back("genc");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(M);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(M);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Mgen);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Mgen);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Mgen);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_wei_dsn_bin_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        std::vector<double> C;
        size_t C_d_0_max__ = M;
        C.reserve(C_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < C_d_0_max__; ++d_0__) {
            C.push_back(in__.scalar_lb_constrain(0));
        }
        size_t C_k_0_max__ = M;
        for (size_t k_0__ = 0; k_0__ < C_k_0_max__; ++k_0__) {
            vars__.push_back(C[k_0__]);
        }
        std::vector<double> w;
        size_t w_d_0_max__ = M;
        w.reserve(w_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < w_d_0_max__; ++d_0__) {
            w.push_back(in__.scalar_lb_constrain(0));
        }
        size_t w_k_0_max__ = M;
        for (size_t k_0__ = 0; k_0__ < w_k_0_max__; ++k_0__) {
            vars__.push_back(w[k_0__]);
        }
        double cloc = in__.scalar_lb_constrain(0);
        vars__.push_back(cloc);
        double wloc = in__.scalar_lb_constrain(0);
        vars__.push_back(wloc);
        double csc = in__.scalar_lb_constrain(0);
        vars__.push_back(csc);
        double wsc = in__.scalar_lb_constrain(0);
        vars__.push_back(wsc);
        double csh = in__.scalar_lb_constrain(0);
        vars__.push_back(csh);
        double wsh = in__.scalar_lb_constrain(0);
        vars__.push_back(wsh);
        double pn = in__.scalar_lub_constrain(0, 1);
        vars__.push_back(pn);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 127;
            validate_non_negative_index("Ngen", "Mgen", Mgen);
            std::vector<int> Ngen(Mgen, int(0));
            stan::math::fill(Ngen, std::numeric_limits<int>::min());
            current_statement_begin__ = 128;
            validate_non_negative_index("Cgen", "Mgen", Mgen);
            std::vector<double> Cgen(Mgen, double(0));
            stan::math::initialize(Cgen, DUMMY_VAR__);
            stan::math::fill(Cgen, DUMMY_VAR__);
            current_statement_begin__ = 129;
            validate_non_negative_index("wgen", "Mgen", Mgen);
            std::vector<double> wgen(Mgen, double(0));
            stan::math::initialize(wgen, DUMMY_VAR__);
            stan::math::fill(wgen, DUMMY_VAR__);
            current_statement_begin__ = 142;
            int count_w;
            (void) count_w;  // dummy to suppress unused var warning
            stan::math::fill(count_w, std::numeric_limits<int>::min());
            current_statement_begin__ = 143;
            double genw;
            (void) genw;  // dummy to suppress unused var warning
            stan::math::initialize(genw, DUMMY_VAR__);
            stan::math::fill(genw, DUMMY_VAR__);
            current_statement_begin__ = 144;
            int count_c;
            (void) count_c;  // dummy to suppress unused var warning
            stan::math::fill(count_c, std::numeric_limits<int>::min());
            current_statement_begin__ = 145;
            double genc;
            (void) genc;  // dummy to suppress unused var warning
            stan::math::initialize(genc, DUMMY_VAR__);
            stan::math::fill(genc, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 147;
            stan::math::assign(count_c, 0);
            current_statement_begin__ = 148;
            while (as_bool(logical_lt(count_c, Mgen))) {
                current_statement_begin__ = 149;
                stan::math::assign(genc, skew_normal_rng(cloc, csc, csh, base_rng__));
                current_statement_begin__ = 150;
                if (as_bool(logical_gt(genc, 0))) {
                    current_statement_begin__ = 151;
                    stan::math::assign(count_c, (count_c + 1));
                    current_statement_begin__ = 152;
                    stan::model::assign(Cgen, 
                                stan::model::cons_list(stan::model::index_uni(count_c), stan::model::nil_index_list()), 
                                genc, 
                                "assigning variable Cgen");
                }
            }
            current_statement_begin__ = 157;
            stan::math::assign(count_w, 0);
            current_statement_begin__ = 158;
            while (as_bool(logical_lt(count_w, Mgen))) {
                current_statement_begin__ = 159;
                stan::math::assign(genw, skew_normal_rng(wloc, wsc, wsh, base_rng__));
                current_statement_begin__ = 160;
                if (as_bool(logical_gt(genw, 0))) {
                    current_statement_begin__ = 161;
                    stan::math::assign(count_w, (count_w + 1));
                    current_statement_begin__ = 162;
                    stan::model::assign(wgen, 
                                stan::model::cons_list(stan::model::index_uni(count_w), stan::model::nil_index_list()), 
                                genw, 
                                "assigning variable wgen");
                }
            }
            current_statement_begin__ = 166;
            for (int m = 1; m <= Mgen; ++m) {
                current_statement_begin__ = 173;
                stan::model::assign(Ngen, 
                            stan::model::cons_list(stan::model::index_uni(m), stan::model::nil_index_list()), 
                            binomial_rng(Nt, pn, base_rng__), 
                            "assigning variable Ngen");
            }
            // validate, write generated quantities
            current_statement_begin__ = 127;
            size_t Ngen_i_0_max__ = Mgen;
            for (size_t i_0__ = 0; i_0__ < Ngen_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "Ngen[i_0__]", Ngen[i_0__], 0);
            }
            size_t Ngen_k_0_max__ = Mgen;
            for (size_t k_0__ = 0; k_0__ < Ngen_k_0_max__; ++k_0__) {
                vars__.push_back(Ngen[k_0__]);
            }
            current_statement_begin__ = 128;
            size_t Cgen_i_0_max__ = Mgen;
            for (size_t i_0__ = 0; i_0__ < Cgen_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "Cgen[i_0__]", Cgen[i_0__], 0);
            }
            size_t Cgen_k_0_max__ = Mgen;
            for (size_t k_0__ = 0; k_0__ < Cgen_k_0_max__; ++k_0__) {
                vars__.push_back(Cgen[k_0__]);
            }
            current_statement_begin__ = 129;
            size_t wgen_i_0_max__ = Mgen;
            for (size_t i_0__ = 0; i_0__ < wgen_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "wgen[i_0__]", wgen[i_0__], 0);
            }
            size_t wgen_k_0_max__ = Mgen;
            for (size_t k_0__ = 0; k_0__ < wgen_k_0_max__; ++k_0__) {
                vars__.push_back(wgen[k_0__]);
            }
            current_statement_begin__ = 142;
            vars__.push_back(count_w);
            current_statement_begin__ = 143;
            vars__.push_back(genw);
            current_statement_begin__ = 144;
            vars__.push_back(count_c);
            current_statement_begin__ = 145;
            vars__.push_back(genc);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_wei_dsn_bin";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t C_k_0_max__ = M;
        for (size_t k_0__ = 0; k_0__ < C_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "C" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t w_k_0_max__ = M;
        for (size_t k_0__ = 0; k_0__ < w_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "w" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "cloc";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "wloc";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "csc";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "wsc";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "csh";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "wsh";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "pn";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
        size_t Ngen_k_0_max__ = Mgen;
        for (size_t k_0__ = 0; k_0__ < Ngen_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Ngen" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t Cgen_k_0_max__ = Mgen;
        for (size_t k_0__ = 0; k_0__ < Cgen_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Cgen" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t wgen_k_0_max__ = Mgen;
        for (size_t k_0__ = 0; k_0__ < wgen_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "wgen" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "count_w";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "genw";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "count_c";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "genc";
        param_names__.push_back(param_name_stream__.str());
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t C_k_0_max__ = M;
        for (size_t k_0__ = 0; k_0__ < C_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "C" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t w_k_0_max__ = M;
        for (size_t k_0__ = 0; k_0__ < w_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "w" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "cloc";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "wloc";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "csc";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "wsc";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "csh";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "wsh";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "pn";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
        size_t Ngen_k_0_max__ = Mgen;
        for (size_t k_0__ = 0; k_0__ < Ngen_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Ngen" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t Cgen_k_0_max__ = Mgen;
        for (size_t k_0__ = 0; k_0__ < Cgen_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "Cgen" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t wgen_k_0_max__ = Mgen;
        for (size_t k_0__ = 0; k_0__ < wgen_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "wgen" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "count_w";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "genw";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "count_c";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "genc";
        param_names__.push_back(param_name_stream__.str());
    }
}; // model
}  // namespace
typedef model_wei_dsn_bin_namespace::model_wei_dsn_bin stan_model;
#endif
