// Generated by rstantools.  Do not edit by hand.

/*
    hbevr is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    hbevr is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with hbevr.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_pot_ppp_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_pot_ppp");
    reader.add_event(140, 138, "end", "model_pot_ppp");
    return reader;
}
template <bool propto, typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
gpareto_lpdf(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
                 const T1__& ymin,
                 const T2__& k,
                 const T3__& sigma, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 7;
        int N(0);
        (void) N;  // dummy to suppress unused var warning
        stan::math::fill(N, std::numeric_limits<int>::min());
        stan::math::assign(N,rows(y));
        current_statement_begin__ = 8;
        local_scalar_t__ inv_k(DUMMY_VAR__);
        (void) inv_k;  // dummy to suppress unused var warning
        stan::math::initialize(inv_k, DUMMY_VAR__);
        stan::math::fill(inv_k, DUMMY_VAR__);
        stan::math::assign(inv_k,inv(k));
        current_statement_begin__ = 9;
        if (as_bool((primitive_value(logical_lt(k, 0)) && primitive_value(logical_gt((max(subtract(y, ymin)) / sigma), -(inv_k)))))) {
            current_statement_begin__ = 10;
            std::stringstream errmsg_stream__;
            errmsg_stream__ << "k<0 and max(y-ymin)/sigma > -1/k; found k, sigma =";
            errmsg_stream__ << k;
            errmsg_stream__ << sigma;
            throw std::domain_error(errmsg_stream__.str());
        }
        current_statement_begin__ = 11;
        if (as_bool(logical_lte(sigma, 0))) {
            current_statement_begin__ = 12;
            std::stringstream errmsg_stream__;
            errmsg_stream__ << "sigma<=0; found sigma =";
            errmsg_stream__ << sigma;
            throw std::domain_error(errmsg_stream__.str());
        }
        current_statement_begin__ = 13;
        if (as_bool(logical_gt(stan::math::fabs(k), 1e-15))) {
            current_statement_begin__ = 14;
            return stan::math::promote_scalar<fun_return_scalar_t__>(((-((1 + inv_k)) * sum(stan::math::log1p(multiply(subtract(y, ymin), (k / sigma))))) - (N * stan::math::log(sigma))));
        } else {
            current_statement_begin__ = 16;
            return stan::math::promote_scalar<fun_return_scalar_t__>(((-(sum(subtract(y, ymin))) / sigma) - (N * stan::math::log(sigma))));
        }
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
template <typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
gpareto_lpdf(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
                 const T1__& ymin,
                 const T2__& k,
                 const T3__& sigma, std::ostream* pstream__) {
    return gpareto_lpdf<false>(y,ymin,k,sigma, pstream__);
}
struct gpareto_lpdf_functor__ {
    template <bool propto, typename T0__, typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
                 const T1__& ymin,
                 const T2__& k,
                 const T3__& sigma, std::ostream* pstream__) const {
        return gpareto_lpdf(y, ymin, k, sigma, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
gpareto_lcdf(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
                 const T1__& ymin,
                 const T2__& k,
                 const T3__& sigma, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 20;
        local_scalar_t__ inv_k(DUMMY_VAR__);
        (void) inv_k;  // dummy to suppress unused var warning
        stan::math::initialize(inv_k, DUMMY_VAR__);
        stan::math::fill(inv_k, DUMMY_VAR__);
        stan::math::assign(inv_k,inv(k));
        current_statement_begin__ = 21;
        if (as_bool((primitive_value(logical_lt(k, 0)) && primitive_value(logical_gt((max(subtract(y, ymin)) / sigma), -(inv_k)))))) {
            current_statement_begin__ = 22;
            std::stringstream errmsg_stream__;
            errmsg_stream__ << "k<0 and max(y-ymin)/sigma > -1/k; found k, sigma =";
            errmsg_stream__ << k;
            errmsg_stream__ << sigma;
            throw std::domain_error(errmsg_stream__.str());
        }
        current_statement_begin__ = 23;
        if (as_bool(logical_lte(sigma, 0))) {
            current_statement_begin__ = 24;
            std::stringstream errmsg_stream__;
            errmsg_stream__ << "sigma<=0; found sigma =";
            errmsg_stream__ << sigma;
            throw std::domain_error(errmsg_stream__.str());
        }
        current_statement_begin__ = 25;
        if (as_bool(logical_gt(stan::math::fabs(k), 1e-15))) {
            current_statement_begin__ = 26;
            return stan::math::promote_scalar<fun_return_scalar_t__>(sum(log1m_exp(multiply(-(inv_k), stan::math::log1p(multiply(subtract(y, ymin), (k / sigma)))))));
        } else {
            current_statement_begin__ = 28;
            return stan::math::promote_scalar<fun_return_scalar_t__>(sum(log1m_exp(divide(minus(subtract(y, ymin)), sigma))));
        }
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct gpareto_lcdf_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
                 const T1__& ymin,
                 const T2__& k,
                 const T3__& sigma, std::ostream* pstream__) const {
        return gpareto_lcdf(y, ymin, k, sigma, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
gpareto_lccdf(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
                  const T1__& ymin,
                  const T2__& k,
                  const T3__& sigma, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 32;
        local_scalar_t__ inv_k(DUMMY_VAR__);
        (void) inv_k;  // dummy to suppress unused var warning
        stan::math::initialize(inv_k, DUMMY_VAR__);
        stan::math::fill(inv_k, DUMMY_VAR__);
        stan::math::assign(inv_k,inv(k));
        current_statement_begin__ = 33;
        if (as_bool((primitive_value(logical_lt(k, 0)) && primitive_value(logical_gt((max(subtract(y, ymin)) / sigma), -(inv_k)))))) {
            current_statement_begin__ = 34;
            std::stringstream errmsg_stream__;
            errmsg_stream__ << "k<0 and max(y-ymin)/sigma > -1/k; found k, sigma =";
            errmsg_stream__ << k;
            errmsg_stream__ << sigma;
            throw std::domain_error(errmsg_stream__.str());
        }
        current_statement_begin__ = 35;
        if (as_bool(logical_lte(sigma, 0))) {
            current_statement_begin__ = 36;
            std::stringstream errmsg_stream__;
            errmsg_stream__ << "sigma<=0; found sigma =";
            errmsg_stream__ << sigma;
            throw std::domain_error(errmsg_stream__.str());
        }
        current_statement_begin__ = 37;
        if (as_bool(logical_gt(stan::math::fabs(k), 1e-15))) {
            current_statement_begin__ = 38;
            return stan::math::promote_scalar<fun_return_scalar_t__>((-(inv_k) * sum(stan::math::log1p(multiply(subtract(y, ymin), (k / sigma))))));
        } else {
            current_statement_begin__ = 40;
            return stan::math::promote_scalar<fun_return_scalar_t__>((-(sum(subtract(y, ymin))) / sigma));
        }
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct gpareto_lccdf_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
                  const T1__& ymin,
                  const T2__& k,
                  const T3__& sigma, std::ostream* pstream__) const {
        return gpareto_lccdf(y, ymin, k, sigma, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, class RNG>
typename boost::math::tools::promote_args<T0__, T1__, T2__>::type
gpareto_rng(const T0__& ymin,
                const T1__& k,
                const T2__& sigma, RNG& base_rng__, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        current_statement_begin__ = 44;
        if (as_bool(logical_lte(sigma, 0))) {
            current_statement_begin__ = 45;
            std::stringstream errmsg_stream__;
            errmsg_stream__ << "sigma<=0; found sigma =";
            errmsg_stream__ << sigma;
            throw std::domain_error(errmsg_stream__.str());
        }
        current_statement_begin__ = 46;
        if (as_bool(logical_gt(stan::math::fabs(k), 1e-15))) {
            current_statement_begin__ = 47;
            return stan::math::promote_scalar<fun_return_scalar_t__>((ymin + (((pow(uniform_rng(0, 1, base_rng__), -(k)) - 1) * sigma) / k)));
        } else {
            current_statement_begin__ = 49;
            return stan::math::promote_scalar<fun_return_scalar_t__>((ymin - (sigma * stan::math::log(uniform_rng(0, 1, base_rng__)))));
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct gpareto_rng_functor__ {
    template <typename T0__, typename T1__, typename T2__, class RNG>
        typename boost::math::tools::promote_args<T0__, T1__, T2__>::type
    operator()(const T0__& ymin,
                const T1__& k,
                const T2__& sigma, RNG& base_rng__, std::ostream* pstream__) const {
        return gpareto_rng(ymin, k, sigma, base_rng__, pstream__);
    }
};
template <bool propto, typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
gev_lpdf(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
             const T1__& mu,
             const T2__& k,
             const T3__& psi, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 55;
        local_scalar_t__ N(DUMMY_VAR__);
        (void) N;  // dummy to suppress unused var warning
        stan::math::initialize(N, DUMMY_VAR__);
        stan::math::fill(N, DUMMY_VAR__);
        stan::math::assign(N,rows(y));
        current_statement_begin__ = 56;
        local_scalar_t__ inv_k(DUMMY_VAR__);
        (void) inv_k;  // dummy to suppress unused var warning
        stan::math::initialize(inv_k, DUMMY_VAR__);
        stan::math::fill(inv_k, DUMMY_VAR__);
        stan::math::assign(inv_k,inv(k));
        current_statement_begin__ = 57;
        if (as_bool((primitive_value(logical_lt(k, 0)) && primitive_value(logical_gt((max(subtract(y, mu)) / psi), -(inv_k)))))) {
            current_statement_begin__ = 58;
            return stan::math::promote_scalar<fun_return_scalar_t__>((-(9) * stan::math::log(10)));
        }
        current_statement_begin__ = 59;
        if (as_bool((primitive_value(logical_gt(k, 0)) && primitive_value(logical_lt((min(subtract(y, mu)) / psi), -(inv_k)))))) {
            current_statement_begin__ = 60;
            return stan::math::promote_scalar<fun_return_scalar_t__>((-(9) * stan::math::log(10)));
        }
        current_statement_begin__ = 61;
        if (as_bool(logical_lte(psi, 0))) {
            current_statement_begin__ = 62;
            std::stringstream errmsg_stream__;
            errmsg_stream__ << "psi<=0; found psi =";
            errmsg_stream__ << psi;
            throw std::domain_error(errmsg_stream__.str());
        }
        current_statement_begin__ = 63;
        if (as_bool(logical_gt(stan::math::fabs(k), 1e-15))) {
            current_statement_begin__ = 65;
            return stan::math::promote_scalar<fun_return_scalar_t__>((((-(N) * stan::math::log(psi)) - ((1 + inv_k) * sum(stan::math::log1p(multiply(subtract(y, mu), (k / psi)))))) - sum(stan::math::exp(multiply(-(inv_k), stan::math::log1p(multiply(subtract(y, mu), (k / psi))))))));
        } else {
            current_statement_begin__ = 69;
            return stan::math::promote_scalar<fun_return_scalar_t__>(((-(N) * stan::math::log(psi)) - sum(add(divide(subtract(y, mu), psi), stan::math::exp(divide(minus(subtract(y, mu)), psi))))));
        }
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
template <typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
gev_lpdf(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
             const T1__& mu,
             const T2__& k,
             const T3__& psi, std::ostream* pstream__) {
    return gev_lpdf<false>(y,mu,k,psi, pstream__);
}
struct gev_lpdf_functor__ {
    template <bool propto, typename T0__, typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
             const T1__& mu,
             const T2__& k,
             const T3__& psi, std::ostream* pstream__) const {
        return gev_lpdf(y, mu, k, psi, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, class RNG>
typename boost::math::tools::promote_args<T0__, T1__, T2__>::type
gev_rng(const T0__& mu,
            const T1__& k,
            const T2__& psi, RNG& base_rng__, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        current_statement_begin__ = 72;
        if (as_bool(logical_lte(psi, 0))) {
            current_statement_begin__ = 73;
            std::stringstream errmsg_stream__;
            errmsg_stream__ << "[psi<=0; found psi =";
            errmsg_stream__ << psi;
            throw std::domain_error(errmsg_stream__.str());
        }
        current_statement_begin__ = 74;
        if (as_bool(logical_gt(stan::math::fabs(k), 1e-15))) {
            current_statement_begin__ = 75;
            return stan::math::promote_scalar<fun_return_scalar_t__>((mu + ((psi / k) * (-(1) + stan::math::exp((-(k) * stan::math::log(-(stan::math::log(uniform_rng(0, 1, base_rng__))))))))));
        } else {
            current_statement_begin__ = 77;
            return stan::math::promote_scalar<fun_return_scalar_t__>((mu - (psi * stan::math::log(-(stan::math::log(uniform_rng(0, 1, base_rng__)))))));
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct gev_rng_functor__ {
    template <typename T0__, typename T1__, typename T2__, class RNG>
        typename boost::math::tools::promote_args<T0__, T1__, T2__>::type
    operator()(const T0__& mu,
            const T1__& k,
            const T2__& psi, RNG& base_rng__, std::ostream* pstream__) const {
        return gev_rng(mu, k, psi, base_rng__, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_pot_ppp : public prob_grad {
private:
        double ymin;
        int M;
        int My;
        vector_d y;
        std::vector<int> N;
        int Mgen;
        std::vector<double> maxima;
        std::vector<double> pr_sigma;
        std::vector<double> pr_k;
        std::vector<double> pr_lambda;
        double ymax;
public:
    model_pot_ppp(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_pot_ppp(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_pot_ppp_namespace::model_pot_ppp";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 81;
            context__.validate_dims("data initialization", "ymin", "double", context__.to_vec());
            ymin = double(0);
            vals_r__ = context__.vals_r("ymin");
            pos__ = 0;
            ymin = vals_r__[pos__++];
            current_statement_begin__ = 82;
            context__.validate_dims("data initialization", "M", "int", context__.to_vec());
            M = int(0);
            vals_i__ = context__.vals_i("M");
            pos__ = 0;
            M = vals_i__[pos__++];
            check_greater_or_equal(function__, "M", M, 0);
            current_statement_begin__ = 83;
            context__.validate_dims("data initialization", "My", "int", context__.to_vec());
            My = int(0);
            vals_i__ = context__.vals_i("My");
            pos__ = 0;
            My = vals_i__[pos__++];
            check_greater_or_equal(function__, "My", My, 1);
            current_statement_begin__ = 84;
            validate_non_negative_index("y", "M", M);
            context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec(M));
            y = Eigen::Matrix<double, Eigen::Dynamic, 1>(M);
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_j_1_max__ = M;
            for (size_t j_1__ = 0; j_1__ < y_j_1_max__; ++j_1__) {
                y(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "y", y, ymin);
            current_statement_begin__ = 85;
            validate_non_negative_index("N", "My", My);
            context__.validate_dims("data initialization", "N", "int", context__.to_vec(My));
            N = std::vector<int>(My, int(0));
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            size_t N_k_0_max__ = My;
            for (size_t k_0__ = 0; k_0__ < N_k_0_max__; ++k_0__) {
                N[k_0__] = vals_i__[pos__++];
            }
            size_t N_i_0_max__ = My;
            for (size_t i_0__ = 0; i_0__ < N_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "N[i_0__]", N[i_0__], 0);
            }
            current_statement_begin__ = 86;
            context__.validate_dims("data initialization", "Mgen", "int", context__.to_vec());
            Mgen = int(0);
            vals_i__ = context__.vals_i("Mgen");
            pos__ = 0;
            Mgen = vals_i__[pos__++];
            current_statement_begin__ = 87;
            validate_non_negative_index("maxima", "My", My);
            context__.validate_dims("data initialization", "maxima", "double", context__.to_vec(My));
            maxima = std::vector<double>(My, double(0));
            vals_r__ = context__.vals_r("maxima");
            pos__ = 0;
            size_t maxima_k_0_max__ = My;
            for (size_t k_0__ = 0; k_0__ < maxima_k_0_max__; ++k_0__) {
                maxima[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 88;
            validate_non_negative_index("pr_sigma", "2", 2);
            context__.validate_dims("data initialization", "pr_sigma", "double", context__.to_vec(2));
            pr_sigma = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("pr_sigma");
            pos__ = 0;
            size_t pr_sigma_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < pr_sigma_k_0_max__; ++k_0__) {
                pr_sigma[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 89;
            validate_non_negative_index("pr_k", "2", 2);
            context__.validate_dims("data initialization", "pr_k", "double", context__.to_vec(2));
            pr_k = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("pr_k");
            pos__ = 0;
            size_t pr_k_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < pr_k_k_0_max__; ++k_0__) {
                pr_k[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 90;
            validate_non_negative_index("pr_lambda", "2", 2);
            context__.validate_dims("data initialization", "pr_lambda", "double", context__.to_vec(2));
            pr_lambda = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("pr_lambda");
            pos__ = 0;
            size_t pr_lambda_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < pr_lambda_k_0_max__; ++k_0__) {
                pr_lambda[k_0__] = vals_r__[pos__++];
            }
            // initialize transformed data variables
            current_statement_begin__ = 93;
            ymax = double(0);
            stan::math::fill(ymax, DUMMY_VAR__);
            // execute transformed data statements
            current_statement_begin__ = 94;
            stan::math::assign(ymax, max(y));
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 97;
            num_params_r__ += 1;
            current_statement_begin__ = 98;
            num_params_r__ += 1;
            current_statement_begin__ = 99;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_pot_ppp() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 97;
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 98;
        if (!(context__.contains_r("k")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable k missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("k");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "k", "double", context__.to_vec());
        double k(0);
        k = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain((-(sigma) / (ymax - ymin)), k);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable k: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 99;
        if (!(context__.contains_r("lambda")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lambda missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lambda");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "lambda", "double", context__.to_vec());
        double lambda(0);
        lambda = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, lambda);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lambda: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 97;
            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0, lp__);
            else
                sigma = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 98;
            local_scalar_t__ k;
            (void) k;  // dummy to suppress unused var warning
            if (jacobian__)
                k = in__.scalar_lb_constrain((-(sigma) / (ymax - ymin)), lp__);
            else
                k = in__.scalar_lb_constrain((-(sigma) / (ymax - ymin)));
            current_statement_begin__ = 99;
            local_scalar_t__ lambda;
            (void) lambda;  // dummy to suppress unused var warning
            if (jacobian__)
                lambda = in__.scalar_lb_constrain(0, lp__);
            else
                lambda = in__.scalar_lb_constrain(0);
            // transformed parameters
            current_statement_begin__ = 102;
            local_scalar_t__ psi;
            (void) psi;  // dummy to suppress unused var warning
            stan::math::initialize(psi, DUMMY_VAR__);
            stan::math::fill(psi, DUMMY_VAR__);
            current_statement_begin__ = 103;
            local_scalar_t__ mu;
            (void) mu;  // dummy to suppress unused var warning
            stan::math::initialize(mu, DUMMY_VAR__);
            stan::math::fill(mu, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 104;
            stan::math::assign(mu, (ymin + ((sigma / k) * (pow(lambda, k) - 1))));
            current_statement_begin__ = 105;
            stan::math::assign(psi, (sigma * pow(lambda, k)));
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 102;
            if (stan::math::is_uninitialized(psi)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: psi";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable psi: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            check_greater_or_equal(function__, "psi", psi, 0);
            current_statement_begin__ = 103;
            if (stan::math::is_uninitialized(mu)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: mu";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable mu: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            // model body
            current_statement_begin__ = 109;
            lp_accum__.add(gamma_log<propto__>(lambda, get_base1(pr_lambda, 1, "pr_lambda", 1), get_base1(pr_lambda, 2, "pr_lambda", 1)));
            current_statement_begin__ = 110;
            for (int m = 1; m <= My; ++m) {
                current_statement_begin__ = 111;
                lp_accum__.add(poisson_log(get_base1(N, m, "N", 1), lambda));
            }
            current_statement_begin__ = 116;
            lp_accum__.add(normal_log<propto__>(k, get_base1(pr_k, 1, "pr_k", 1), get_base1(pr_k, 2, "pr_k", 1)));
            current_statement_begin__ = 118;
            lp_accum__.add(gamma_log<propto__>(sigma, get_base1(pr_sigma, 1, "pr_sigma", 1), get_base1(pr_sigma, 2, "pr_sigma", 1)));
            current_statement_begin__ = 120;
            lp_accum__.add(gpareto_lpdf<propto__>(y, ymin, k, sigma, pstream__));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("sigma");
        names__.push_back("k");
        names__.push_back("lambda");
        names__.push_back("psi");
        names__.push_back("mu");
        names__.push_back("yrep");
        names__.push_back("log_lik");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Mgen);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(My);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_pot_ppp_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double sigma = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma);
        double k = in__.scalar_lb_constrain((-(sigma) / (ymax - ymin)));
        vars__.push_back(k);
        double lambda = in__.scalar_lb_constrain(0);
        vars__.push_back(lambda);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 102;
            double psi;
            (void) psi;  // dummy to suppress unused var warning
            stan::math::initialize(psi, DUMMY_VAR__);
            stan::math::fill(psi, DUMMY_VAR__);
            current_statement_begin__ = 103;
            double mu;
            (void) mu;  // dummy to suppress unused var warning
            stan::math::initialize(mu, DUMMY_VAR__);
            stan::math::fill(mu, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 104;
            stan::math::assign(mu, (ymin + ((sigma / k) * (pow(lambda, k) - 1))));
            current_statement_begin__ = 105;
            stan::math::assign(psi, (sigma * pow(lambda, k)));
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 102;
            check_greater_or_equal(function__, "psi", psi, 0);
            // write transformed parameters
            if (include_tparams__) {
                vars__.push_back(psi);
                vars__.push_back(mu);
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 125;
            validate_non_negative_index("yrep", "Mgen", Mgen);
            std::vector<double> yrep(Mgen, double(0));
            stan::math::initialize(yrep, DUMMY_VAR__);
            stan::math::fill(yrep, DUMMY_VAR__);
            current_statement_begin__ = 126;
            validate_non_negative_index("log_lik", "My", My);
            std::vector<double> log_lik(My, double(0));
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 130;
            for (int i = 1; i <= Mgen; ++i) {
                current_statement_begin__ = 131;
                stan::model::assign(yrep, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            gev_rng(mu, k, psi, base_rng__, pstream__), 
                            "assigning variable yrep");
            }
            current_statement_begin__ = 133;
            for (int i = 1; i <= My; ++i) {
                current_statement_begin__ = 134;
                stan::model::assign(log_lik, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            gev_lpdf(rep_vector(get_base1(maxima, i, "maxima", 1), 1), mu, k, psi, pstream__), 
                            "assigning variable log_lik");
            }
            // validate, write generated quantities
            current_statement_begin__ = 125;
            size_t yrep_k_0_max__ = Mgen;
            for (size_t k_0__ = 0; k_0__ < yrep_k_0_max__; ++k_0__) {
                vars__.push_back(yrep[k_0__]);
            }
            current_statement_begin__ = 126;
            size_t log_lik_k_0_max__ = My;
            for (size_t k_0__ = 0; k_0__ < log_lik_k_0_max__; ++k_0__) {
                vars__.push_back(log_lik[k_0__]);
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_pot_ppp";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "k";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "lambda";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "psi";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "mu";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
        size_t yrep_k_0_max__ = Mgen;
        for (size_t k_0__ = 0; k_0__ < yrep_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "yrep" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_k_0_max__ = My;
        for (size_t k_0__ = 0; k_0__ < log_lik_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "k";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "lambda";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "psi";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "mu";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
        size_t yrep_k_0_max__ = Mgen;
        for (size_t k_0__ = 0; k_0__ < yrep_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "yrep" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_k_0_max__ = My;
        for (size_t k_0__ = 0; k_0__ < log_lik_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_pot_ppp_namespace::model_pot_ppp stan_model;
#endif
