# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("gev", "gev_nobounds", "mix_dyn_bin", "mix_dyp_bin", "mix_sta_bin", "pot_ppp", "wei_dex_bin", "wei_dgu_bbn", "wei_dgu_bin", "wei_dsn_bin", "wei_dyl_bin", "wei_dyn_bbn", "wei_dyn_bin", "wei_sta_bbn", "wei_sta_bin")

# load each stan module
Rcpp::loadModule("stan_fit4gev_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gev_nobounds_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mix_dyn_bin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mix_dyp_bin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mix_sta_bin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4pot_ppp_mod", what = TRUE)
Rcpp::loadModule("stan_fit4wei_dex_bin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4wei_dgu_bbn_mod", what = TRUE)
Rcpp::loadModule("stan_fit4wei_dgu_bin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4wei_dsn_bin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4wei_dyl_bin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4wei_dyn_bbn_mod", what = TRUE)
Rcpp::loadModule("stan_fit4wei_dyn_bin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4wei_sta_bbn_mod", what = TRUE)
Rcpp::loadModule("stan_fit4wei_sta_bin_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
